### ISSUE TITLE
flixius compile error

### ISSUE THREAD

**Issue by srukle** [HaxeFlixel/flixel-demos#208]
flixel-addons: git [dev:/usr/lib/haxe/lib/flixel-addons/git]
flixel-demos: git [dev:/usr/lib/haxe/lib/flixel-demos/git]
flixel-ui: git [dev:/usr/lib/haxe/lib/flixel-ui/git]
flixel: git 3.3.11 [dev:/usr/lib/haxe/lib/flixel/git]
hxcpp: [3.2.180]
lime-samples: [2.6.0]
lime: [2.6.9]
openfl: [3.3.9]

-------------------------

Error: ./src/flixel/addons/ui/FlxUITooltipManager.cpp: In member function ‘virtual Void flixel::addons::ui::FlxUITooltipManager_obj::add(flixel::FlxObject, Dynamic)’:
./src/flixel/addons/ui/FlxUITooltipManager.cpp:507:10: error: ‘class flixel::addons::ui::interfaces::IFlxUIButton_obj’ has no member named ‘set_x’
     btn->set_x(tmp9);
          ^
./src/flixel/addons/ui/FlxUITooltipManager.cpp:511:10: error: ‘class flixel::addons::ui::interfaces::IFlxUIButton_obj’ has no member named ‘set_y’
     btn->set_y(tmp10);
          ^
./src/flixel/addons/ui/FlxUITooltipManager.cpp:573:16: error: ‘class flixel::addons::ui::interfaces::IFlxUIButton_obj’ has no member named ‘set_x’
     tmp8->btn->set_x(tmp9);
                ^
./src/flixel/addons/ui/FlxUITooltipManager.cpp:579:17: error: ‘class flixel::addons::ui::interfaces::IFlxUIButton_obj’ has no member named ‘set_y’
     tmp10->btn->set_y(tmp11);
                 ^
./src/flixel/addons/ui/FlxUITooltipManager.cpp: In member function ‘virtual Void flixel::addons::ui::FlxUITooltipManager_obj::update(Float)’:
./src/flixel/addons/ui/FlxUITooltipManager.cpp:743:10: error: ‘class flixel::addons::ui::interfaces::IFlxUIButton_obj’ has no member named ‘set_x’
     btn->set_x(tmp10);
          ^
./src/flixel/addons/ui/FlxUITooltipManager.cpp:747:10: error: ‘class flixel::addons::ui::interfaces::IFlxUIButton_obj’ has no member named ‘set_y’
     btn->set_y(tmp11);
          ^
./src/flixel/addons/ui/FlxUITooltipManager.cpp:751:10: error: ‘class flixel::addons::ui::interfaces::IFlxUIButton_obj’ has no member named ‘set_visible’
     btn->set_visible(tmp12);
          ^

**Comment by Gama11** [comment]
Haxe version (`haxe -version`)? Sounds like https://github.com/HaxeFoundation/haxe/issues/4343.

**Comment by srukle** [comment]
haxe 3.2.1

**Comment by Gama11** [comment]
Hm, I guess that bug must've made it into 3.2.1 then... Bummer, not much we can do about it on the flixel side. You're gonna have to use a Haxe version without the bug...

**Comment by larsiusprime** [comment]
@Gama11 Suppose we should bring this up with haxe foundation? Maybe convince them to put out a hotfix?

**Comment by Tiago-Ling** [comment]
That's the same error i got when trying to compile my project with Haxe 3.2.1. 

@MSGhero also had the same problem - looks like **any** HaxeFlixel project will have this problem when trying to compile with 3.2.1. According to him there's a fix already in the development version of Haxe, maybe he can point us to the commit.

**Comment by Mixerman123** [comment]
Huh yeah, I got this too. I won this laptop and was setting it up with Haxe and Haxeflixel. Neko works fine. Thought it was a cpp error, so I installed a bunch of compilers.

Let's hope a fix is soon.

**Comment by Mixerman123** [comment]
Confirming that this works Haxe 2.0

**Comment by MSGhero** [comment]
Well, any Flixel UI project will fail since that's the lib with all the interfaces. The commit is the one Hugh pushed at the end of 4343 from 14 days ago (on phone rn), but any git haxe will be correct now. I thought the issue was just in dev, but I guess they added it to 3.2.1.

**Comment by Gama11** [comment]
The Flixel dev branch now aborts compilation with a somewhat helpful error message when trying to compile a cpp build with Haxe 3.2.1 and flixel-ui. Don't think there's anything else we can do about this issue.
